description = "Full feature Hugo theme build on top of [hugo-theme-sk2](//github.com/J-Siu/hugo-theme-sk2)."
features    = []
homepage    = "https://sk3.jsiu.dev/"
license     = "MIT"
licenselink = "https://github.com/J-Siu/hugo-theme-sk3/blob/master/LICENSE"
min_version = "0.65.0"
name        = "SK3"
tags        = [
	"blog",
	"clean",
	"customizable",
	"dark",
	"disqus",
	"google adsense",
	"google analytics",
	"minimal",
	"mobile",
	"personal",
	"responsive",
	"simple",
]

[author]
homepage = "https://johnsiu.com/"
name     = "John Siu"
